
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map the Java app's port 8080 to localhost
    container_name: java-backend
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map the Nginx port 80 to localhost port 3000
    container_name: react-frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
